
GET http://example.com HTTP/1.1

###

GET http://httpbin.org/json HTTP/1.1

###
POST http://localhost:8000/category_chain/invoke HTTP/1.1


{
    "text": "colors"
}

###

POST https://apejhvxcd.cloud.sealos.io/v1/chat/completions HTTP/2.0
Authorization: 'Bearer sk-xxx'

{
    "model":"gpt-4",
      "messages": [
        {
            "role": "user",
            "content": "如何学习Langchain"
        }
    ],
    "stream": true
}